# Generated by Django 6.0.5 on 2026-05-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=100)),
                ('Book_author', models.CharField(max_length=100)),
                ('Book_journal', models.CharField(max_length=100)),
                ('Book_price', models.IntegerField()),
                ('Book_description', models.CharField(max_length=100)),
                ('Book_rating', models.IntegerField()),
            ],
        ),
    ]
