# Generated by Django 6.0.5 on 2026-05-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_books_mediafile_delete_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
